<?php
/**
 * Title: Header
 * Slug: nano/header
 * Inserter: no
 * Description: Site header — brand mark linking home plus the hamburger navigation. A pattern (not static part markup) so every internal URL is generated by WordPress — the site must work at a domain root, under /studionano/, and after a domain move.
 *
 * @package Nano\ImaginationHub
 */

$nano_home = home_url( '/' );
?>
<!-- wp:group {"tagName":"header","className":"nano-header","layout":{"type":"constrained"}} -->
<header class="wp-block-group nano-header">
	<!-- wp:group {"className":"nano-header__inner","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
	<div class="wp-block-group nano-header__inner">
		<!-- wp:html -->
		<a class="nano-brand" href="<?php echo esc_url( $nano_home ); ?>" aria-label="MIT Imagination Hub — Home">
			<svg class="nano-brand__mark" viewBox="0 0 66.06 42.45" aria-hidden="true">
				<g fill="none" stroke="currentColor" stroke-miterlimit="10">
					<path vector-effect="non-scaling-stroke" d="M34.14,13.42 Q34.24,27.69 34.14,41.95"/>
					<path vector-effect="non-scaling-stroke" d="M66.06,41.95 Q49.85,42.05 33.63,41.95"/>
					<path vector-effect="non-scaling-stroke" d="M19.84,10.35c-.14.28-.37.72-.65,1.23-1.55,2.76-4.46,7.96-8.05,7.9-.15,0-.76-.02-1.45-.31-3.86-1.63-4.09-8.96-4.14-10.55-.02-.63,0-1.14,0-1.39"/>
					<path vector-effect="non-scaling-stroke" d="M19.84,10.38c.14-.28.37-.72.65-1.23,1.55-2.76,4.46-7.96,8.05-7.9.15,0,.76.02,1.45.31,3.86,1.63,4.09,8.96,4.14,10.55.02.63,0,1.14,0,1.39"/>
				</g>
				<circle cx="5.3" cy="5.3" r="5.3" fill="currentColor" stroke="none"/>
			</svg>
		</a>
		<!-- /wp:html -->

		<!-- wp:navigation {"overlayMenu":"always","openSubmenusOnClick":false,"className":"nano-nav","layout":{"type":"flex","justifyContent":"right","flexWrap":"nowrap"},"style":{"spacing":{"blockGap":"2rem"}}} -->
			<!-- wp:home-link {"label":"Home"} /-->
			<!-- wp:navigation-submenu {"label":"Initiatives","url":"<?php echo esc_url( $nano_home . '#initiatives' ); ?>","kind":"custom","isTopLevelLink":true,"className":"nano-sub-initiatives"} -->
				<!-- wp:navigation-link {"label":"Encounters","url":"<?php echo esc_url( nano_initiative_url( 'encounters' ) ); ?>","kind":"custom"} /-->
				<!-- wp:navigation-link {"label":"Resonances","url":"<?php echo esc_url( nano_initiative_url( 'resonances' ) ); ?>","kind":"custom"} /-->
				<!-- wp:navigation-link {"label":"Pedagogies","url":"<?php echo esc_url( nano_initiative_url( 'pedagogies' ) ); ?>","kind":"custom"} /-->
				<!-- wp:navigation-link {"label":"Correlations","url":"<?php echo esc_url( nano_initiative_url( 'correlations' ) ); ?>","kind":"custom"} /-->
			<!-- /wp:navigation-submenu -->
			<!-- wp:navigation-submenu {"label":"Resources","url":"#","kind":"custom","isTopLevelLink":true} -->
				<!-- wp:navigation-link {"label":"Participants","url":"<?php echo esc_url( nano_page_url( 'participants' ) ); ?>","kind":"custom"} /-->
				<!-- wp:navigation-link {"label":"Facilities","url":"<?php echo esc_url( nano_page_url( 'facilities' ) ); ?>","kind":"custom"} /-->
				<!-- wp:navigation-link {"label":"Archive","url":"<?php echo esc_url( nano_page_url( 'archive' ) ); ?>","kind":"custom"} /-->
				<!-- wp:navigation-link {"label":"News","url":"<?php echo esc_url( nano_news_url() ); ?>","kind":"custom"} /-->
			<!-- /wp:navigation-submenu -->
			<!-- wp:navigation-submenu {"label":"About","url":"#","kind":"custom","isTopLevelLink":true} -->
				<!-- wp:navigation-link {"label":"About us","url":"<?php echo esc_url( nano_page_url( 'about-us' ) ); ?>","kind":"custom"} /-->
				<!-- wp:navigation-link {"label":"Support us","url":"<?php echo esc_url( nano_page_url( 'support-us' ) ); ?>","kind":"custom"} /-->
				<!-- wp:navigation-link {"label":"Newsletter","url":"<?php echo esc_url( $nano_home . '#newsletter' ); ?>","kind":"custom"} /-->
				<!-- wp:navigation-link {"label":"Press","url":"<?php echo esc_url( nano_page_url( 'press' ) ); ?>","kind":"custom"} /-->
			<!-- /wp:navigation-submenu -->
		<!-- /wp:navigation -->
	</div>
	<!-- /wp:group -->
</header>
<!-- /wp:group -->
